title: Second Zeitgeist Manifesto
description: A collective vision and manifesto for technology that serves humanity with integrity and purpose
# theme: jekyll-theme-minimal # Comment out since we're using remote_theme
url: "https://stephen-netu.github.io"
baseurl: "/second-zeitgeist"

# Site metadata for SEO/social
lang: en
author:
  name: Second Zeitgeist
logo: /assets/favicon.svg
image: /assets/social-card.svg
twitter_username: secondzeitgeist
github_username: stephen-netu

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-sitemap

remote_theme: pages-themes/minimal@v0.2.0

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .jekyll-cache
  - README.md
  - _site